import '../models/produit.dart';


class DataService {
  static List<Produit> getProduits() {
    return [
      Produit(
        id: '1',
        nom: 'T-Shirt Classic',
        description: 'T-shirt en coton 100% bio, confortable et respirant',
        prix: 29.99,
        categorie: 'T-Shirts',
        taille: 'M',
        couleur: 'Bleu',
        stock: 50,
        imageUrl: '👕',
      ),
      Produit(
        id: '2',
        nom: 'Jean Slim',
        description: 'Jean slim fit, coupe moderne et élégante',
        prix: 79.99,
        categorie: 'Pantalons',
        taille: 'L',
        couleur: 'Noir',
        stock: 30,
        imageUrl: '👖',
      ),
      Produit(
        id: '3',
        nom: 'Robe d\'été',
        description: 'Robe légère parfaite pour l\'été',
        prix: 59.99,
        categorie: 'Robes',
        taille: 'S',
        couleur: 'Rouge',
        stock: 25,
        imageUrl: '👗',
      ),
      Produit(
        id: '4',
        nom: 'Veste en Cuir',
        description: 'Veste en cuir véritable, style intemporel',
        prix: 199.99,
        categorie: 'Vestes',
        taille: 'L',
        couleur: 'Marron',
        stock: 15,
        imageUrl: '🧥',
      ),
      Produit(
        id: '5',
        nom: 'Pull Laine',
        description: 'Pull chaud en laine mérinos',
        prix: 89.99,
        categorie: 'Pulls',
        taille: 'M',
        couleur: 'Gris',
        stock: 40,
        imageUrl: '🧶',
      ),
      Produit(
        id: '6',
        nom: 'Chemise Blanche',
        description: 'Chemise élégante pour toutes occasions',
        prix: 49.99,
        categorie: 'Chemises',
        taille: 'L',
        couleur: 'Blanc',
        stock: 35,
        imageUrl: '👔',
      ),
      Produit(
        id: '7',
        nom: 'Short Sport',
        description: 'Short léger pour activités sportives',
        prix: 34.99,
        categorie: 'Sport',
        taille: 'M',
        couleur: 'Noir',
        stock: 60,
        imageUrl: '🩳',
      ),
      Produit(
        id: '8',
        nom: 'Manteau Hiver',
        description: 'Manteau chaud pour l\'hiver',
        prix: 249.99,
        categorie: 'Manteaux',
        taille: 'L',
        couleur: 'Marine',
        stock: 20,
        imageUrl: '🧥',
      ),
      Produit(
        id: '9',
        nom: 'Pantalon Chino',
        description: 'Pantalon chino confortable et stylé',
        prix: 69.99,
        categorie: 'Pantalons',
        taille: 'M',
        couleur: 'Beige',
        stock: 45,
        imageUrl: '👖',
      ),
      Produit(
        id: '10',
        nom: 'Polo Classique',
        description: 'Polo intemporel en coton piqué',
        prix: 39.99,
        categorie: 'Polos',
        taille: 'L',
        couleur: 'Vert',
        stock: 55,
        imageUrl: '👕',
      ),
    ];
  }
}