// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmAJARCXnaHVKxzpTDZn6kiOz9j6Rgc6I',
    appId: '1:473287002490:web:0f9fdaede572ed3cf66ec3',
    messagingSenderId: '473287002490',
    projectId: 'vetements-app-c13bc',
    authDomain: 'vetements-app-c13bc.firebaseapp.com',
    storageBucket: 'vetements-app-c13bc.firebasestorage.app',
    measurementId: 'G-ZJJ7P5FMLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tLWwhYAB08jd8f94EIasAbF_VRKmtCA',
    appId: '1:473287002490:android:159c80604d0ee164f66ec3',
    messagingSenderId: '473287002490',
    projectId: 'vetements-app-c13bc',
    storageBucket: 'vetements-app-c13bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDc9eDNclItai0OOHKVjbyZdcn9V_arI',
    appId: '1:473287002490:ios:1ade8919f22c0254f66ec3',
    messagingSenderId: '473287002490',
    projectId: 'vetements-app-c13bc',
    storageBucket: 'vetements-app-c13bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDc9eDNclItai0OOHKVjbyZdcn9V_arI',
    appId: '1:473287002490:ios:1ade8919f22c0254f66ec3',
    messagingSenderId: '473287002490',
    projectId: 'vetements-app-c13bc',
    storageBucket: 'vetements-app-c13bc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmAJARCXnaHVKxzpTDZn6kiOz9j6Rgc6I',
    appId: '1:473287002490:web:1bc79b5281de8e92f66ec3',
    messagingSenderId: '473287002490',
    projectId: 'vetements-app-c13bc',
    authDomain: 'vetements-app-c13bc.firebaseapp.com',
    storageBucket: 'vetements-app-c13bc.firebasestorage.app',
    measurementId: 'G-B5QMY6BCK8',
  );
}
